@startuml
'https://plantuml.com/class-diagram

class EstatePlannerContract {
-admin: address
-trustor: address
-beneficiariesPercentages: mapping[address, uint]
-beneficiaries: array[uint]
-percentages: array[uint]
-trustees: array[address]
-activeStatus
-users
-isRevoked: boolean
-totalAmount: uint
-trustName: string

+createContract(trustname, admine, users)
+deleteContract()
+payoutContract()
+enter(beneficiaries: array[string], percentages: array[int], trustees: array[string])
+setBeneficiaries(beneficiary: array[string])
+removeBeneficiary(beneficiary: address)
+getTrustDetails()
+getTotalAmount()
+getTrustName()
}

@enduml